### ISSUE TITLE
Clarify status of project

### ISSUE THREAD

**Issue by FeldrinH** [rkr35/drg#15]
It would be nice to clarify in the readme the status of this project for anybody who might come across it when exploring options for modding DRG.
Is it in active development?
Is it ready to be used in some capacity? If yes, then how?

**Comment by rkr35** [comment]
Hey, @FeldrinH. Thank you for taking a look at the project.

> Is it ready to be used in some capacity? If yes, then how?

Yes, but the use is not pleasant. The project's sole purpose is this: if you have a [`UFunction`](https://raw.githubusercontent.com/rkr35/drg/main/hook/some_native_functions.txt) that you would like to hook at a low-level, then in this `drg` workspace, you can use the [hook crate](https://github.com/rkr35/drg/tree/main/hook) to perform this hook.

The rest of the `drg` workspace contains crates to serve that purpose, e.g., [generating a Rust SDK](https://github.com/rkr35/drg/tree/main/sdk_gen) with `UObjects` and their `UFunction` methods.

> Is it in active development?

Nope. I started the project last year a few months before GSG added official modding support to the game. The project has been educational in many respects, especially in generating an Unreal Engine 4 SDK in Rust and for Rust, but in its current form, the project is not a productive or practical way to create complex DRG mods, owing to its low-level nature.

If you're not already familiar with the community, I happily redirect you to [DRG Modding Discord](https://discord.com/invite/zQMKGTStfa).

The only advantage this project has over the official modding support is the ability to access extremely low-level engine internals, e.g., rendering, netcode. I had at one point the idea of abstracting the low-level hooks of this project into an API that a higher-level scripting interface can access. The ideal here would be a hot-reload Lua or Python interface. That idea, however, will likely never materialize if there isn't a need that the current modding support can't satisfy.
